require('dwang.packer')
require('dwang.core.options')
require('dwang.core.keymaps')
require('dwang.core.colorscheme')
require('dwang.plugins.comment')
require('dwang.plugins.nvim-tree')
require('dwang.plugins.lualine')
require('dwang.plugins.telescope')
